import streamlit as st
from fpdf import FPDF
import textwrap
import matplotlib.pyplot as plt
import pandas as pd

# ---------- PAGE SETUP ----------
st.set_page_config(page_title="BAAMT", layout="wide")

st.title("🧠 BAAMT")
st.subheader("Behavioural Advocacy and Messaging Tool")
st.write(
    "BAAMT helps advocacy organizations design messaging strategies based on the moral values "
    "and behavioral tendencies of their target audience. Complete the assessment below to generate "
    "a detailed behavioural profile and recommended advocacy messaging strategy."
)

# ---------- AUDIENCE CONTEXT ----------
st.markdown("### Audience Information")
st.markdown(
    "Please select the context for your advocacy campaign carefully. "
    "Your selections below will influence the behavioural profiling, messaging strategy, "
    "and advocacy guidance generated by BAAMT."
)
audience = st.selectbox("Select Target Audience", ["General Public", "Professionals", "Students"])
geography = st.selectbox("Select Geography", ["India", "USA", "Other"])
stakeholder = st.selectbox("Select Stakeholder Type", ["Policy Makers", "Civil Society", "Media"])
campaign = st.selectbox("Select Campaign Objective", ["Behaviour Change", "Policy Advocacy", "Awareness"])

# ---------- BEHAVIOURAL ASSESSMENT ----------
st.markdown("### Behavioural Assessment")
st.write("Rate the following statements from 1 (Strongly Disagree) to 5 (Strongly Agree).")

questions = {
    "Preventing suffering should be a top priority in public policy.": 0,
    "Fair treatment matters even if it requires economic trade-offs.": 0,
    "Society functions best when people respect authority and institutions.": 0,
    "Loyalty to one's community should guide political decision-making.": 0,
    "Purity and moral cleanliness are important social values.": 0,
    "Avoiding harm to vulnerable beings is an ethical responsibility.": 0,
    "Rules and laws should be followed even when inconvenient.": 0,
    "People should prioritize fairness in markets and economic systems.": 0,
    "Communities should protect their cultural traditions.": 0,
    "Certain practices are morally wrong regardless of consequences.": 0,
}

responses = {}
for q in questions:
    responses[q] = st.slider(q, 1, 5, 3)

# ---------- CALCULATE MORAL PROFILE ----------
care = (responses[list(questions.keys())[0]] + responses[list(questions.keys())[5]]) / 2
fairness = (responses[list(questions.keys())[1]] + responses[list(questions.keys())[7]]) / 2
authority = (responses[list(questions.keys())[2]] + responses[list(questions.keys())[6]]) / 2
loyalty = (responses[list(questions.keys())[3]] + responses[list(questions.keys())[8]]) / 2
purity = (responses[list(questions.keys())[4]] + responses[list(questions.keys())[9]]) / 2

# ---------- RESULTS ----------
segment = (
    "Mixed moral audiences whose reactions often depend on the framing of your message. "
    "They may respond differently depending on social context, existing coalitions, "
    "and cultural narratives. Messaging should be inclusive and adaptable to local norms."
)

reform = (
    "This audience shows a moderate receptiveness to transformative advocacy narratives. "
    "They may respond well to proposals that challenge existing systems and highlight "
    "the need for deeper social and ethical change in society."
)

risk = (
    "The audience exhibits moderate sensitivity to moral and social risk. "
    "Messaging can focus on presenting empirical evidence, harm reduction, "
    "and ethical progress narratives without being overly cautious."
)

trust = (
    "The audience’s institutional trust is varied. Some members respect authority and institutional guidance, "
    "while others may rely more on community norms and peer influence. "
    "Advocacy should balance factual credibility with culturally resonant messaging."
)

lever = (
    "Primary advocacy messaging should leverage compassion, fairness, and ethical responsibility. "
    "Highlight tangible benefits of ethical behavior and protection of vulnerable populations."
)

geo = (
    f"For the selected geography ({geography}), adjust messaging to local norms, values, "
    "and culturally resonant examples. Consider regional languages, examples, and narratives."
)

strategy = (
    "Campaign strategy should combine evidence-based messaging with storytelling, emphasizing both "
    "moral responsibility and practical steps the audience can take. Timing and channels of communication "
    "should be tailored to the selected stakeholder group."
)

brief = (
    "The full advocacy strategy involves combining moral framing, coalition building, "
    "and targeted outreach. Focus on actionable steps, clear benefits, and aligning messages "
    "with audience values to achieve maximum engagement."
)

framing = (
    "Message framing examples include emphasizing the consequences of inaction, "
    "highlighting the benefits of ethical choices, and showcasing stories of positive change. "
    "Use narratives that humanize the issue and connect emotionally."
)

coalition = (
    "Coalition strategy involves partnering with credible organizations and influencers "
    "to increase reach and trustworthiness. Emphasize common goals and shared values."
)

policy = (
    "Policy pathways should be clearly outlined, showing step-by-step actions that policymakers, "
    "institutions, or community leaders can take. Highlight precedents and successful case studies."
)

risk_analysis = (
    "Opposition risk analysis identifies potential areas of resistance or pushback. "
    "Mitigate risks by anticipating counterarguments, preparing factual responses, "
    "and emphasizing ethical imperatives."
)

# ---------- GENERATE FORMATTED PDF ----------
if st.button("Generate BAAMT Strategy Report"):

    st.subheader("Behavioural Segment")
    st.write(segment)
    st.subheader("Reform Orientation")
    st.write(reform)
    st.subheader("Risk Sensitivity Profile")
    st.write(risk)
    st.subheader("Institutional Trust Orientation")
    st.write(trust)
    st.subheader("Primary Advocacy Lever")
    st.write(lever)
    st.subheader("Geographic Messaging Adjustment")
    st.write(geo)
    st.subheader("Campaign Strategy Plan")
    st.write(strategy)
    st.subheader("Full Advocacy Strategy Brief")
    st.write(brief)

    st.divider()

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    def add_section(title, text):
        pdf.ln(4)
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, title, ln=True)
        pdf.set_font("Arial", "", 11)
        wrapped = textwrap.wrap(text, 90)
        for line in wrapped:
            pdf.cell(0, 7, line, ln=True)

    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "BAAMT Advocacy Strategy Report", ln=True)
    pdf.ln(5)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, f"Audience: {audience}", ln=True)
    pdf.cell(0, 8, f"Geography: {geography}", ln=True)
    pdf.cell(0, 8, f"Stakeholder: {stakeholder}", ln=True)
    pdf.cell(0, 8, f"Campaign Objective: {campaign}", ln=True)

    add_section("Behavioural Segment", segment)
    add_section("Reform Orientation", reform)
    add_section("Risk Sensitivity Profile", risk)
    add_section("Institutional Trust Orientation", trust)
    add_section("Primary Advocacy Lever", lever)
    add_section("Geographic Messaging Adjustment", geo)
    add_section("Campaign Strategy Plan", strategy)
    add_section("Full Advocacy Strategy Brief", brief)
    add_section("Message Framing Examples", framing)
    add_section("Coalition Strategy", coalition)
    add_section("Policy Pathway", policy)
    add_section("Opposition Risk Analysis", risk_analysis)

    pdf_bytes = pdf.output(dest="S").encode("latin-1")

    st.download_button(
        label="Download BAAMT Report (PDF)",
        data=pdf_bytes,
        file_name="BAAMT_report.pdf",
        mime="application/pdf"
    )
